/* ============================================
   ملف بيانات الطلاب/الشهادات
   تم استيراد بيانات الطلاب من ملف الأكواد الرئيسي (studentsData).
   لكل طالب:
   - certificateImageUrl: رابط صورة الشهادة (من postimg.cc)
   - photoUrl: صورة افتراضية (Avatar) باسم الطالب — استبدلها بصورة حقيقية لو حبيت
   الكود (نفس كود الطالب، مثال: 2026001 أو SH-2025-010) هو ما يُدخله الطالب
   في صفحة التحقق (verify.html) لعرض شهادته.
   ============================================ */

const CERTIFICATES_SEED = {
    "2026001": {
        "id": "2026001",
        "secretId": "2026001",
        "name": "هبة الله السيد كامل",
        "courseName": "أخصائي صحة نفسية",
        "grantName": "أخصائي صحة نفسية",
        "graduationYear": "2026",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "2026001",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D9%87%D8%A8%D8%A9&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": "https://i.postimg.cc/tRVwnjjv/IMG-20260727-194410.png"
    },
    "2026002": {
        "id": "2026002",
        "secretId": "2026002",
        "name": "إيمان عبد المنعم محمد",
        "courseName": "التخاطب وعيوب الكلام",
        "grantName": "التخاطب وعيوب الكلام",
        "graduationYear": "2026",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "2026002",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D8%A5%D9%8A%D9%85%D8%A7%D9%86&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": "https://i.postimg.cc/BnhKGRX5/IMG-20260727-192155.png"
    },
    "2026003": {
        "id": "2026003",
        "secretId": "2026003",
        "name": "نرمين فاروق عواد ابراهيم",
        "courseName": "أخصائي صحة نفسية",
        "grantName": "أخصائي صحة نفسية",
        "graduationYear": "2026",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "2026003",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D9%86%D8%B1%D9%85%D9%8A%D9%86&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": "https://i.postimg.cc/7hT77t5p/IMG-20260728-011918.png"
    },
    "2026004": {
        "id": "2026004",
        "secretId": "2026004",
        "name": "السيدة عبد المجيد عبد المطلب",
        "courseName": "أخصائي صحة نفسية",
        "grantName": "أخصائي صحة نفسية",
        "graduationYear": "2026",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "2026004",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D8%A7%D9%84%D8%B3%D9%8A%D8%AF%D8%A9&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": "https://i.postimg.cc/509W6DRC/IMG-20260728-013435.png"
    },
    "2026005": {
        "id": "2026005",
        "secretId": "2026005",
        "name": "فاطمة صديق عبد الغفار ادريس",
        "courseName": "أخصائي صحة نفسية",
        "grantName": "أخصائي صحة نفسية",
        "graduationYear": "2026",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "2026005",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D9%81%D8%A7%D8%B7%D9%85%D8%A9&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": "https://i.postimg.cc/MGNr8NJC/IMG-20260728-013626.png"
    },
    "2026006": {
        "id": "2026006",
        "secretId": "2026006",
        "name": "إسراء صبري تاج السر",
        "courseName": "أخصائي صحة نفسية",
        "grantName": "أخصائي صحة نفسية",
        "graduationYear": "2026",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "2026006",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D8%A5%D8%B3%D8%B1%D8%A7%D8%A1&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": "https://i.postimg.cc/VLvMj6ty/IMG-20260728-013546.png"
    },
    "2026007": {
        "id": "2026007",
        "secretId": "2026007",
        "name": "",
        "courseName": "",
        "grantName": "",
        "graduationYear": "2026",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "2026007",
        "email": "",
        "phone": "",
        "photoUrl": "",
        "certificateImageUrl": ""
    },
    "2026008": {
        "id": "2026008",
        "secretId": "2026008",
        "name": "",
        "courseName": "",
        "grantName": "",
        "graduationYear": "2026",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "2026008",
        "email": "",
        "phone": "",
        "photoUrl": "",
        "certificateImageUrl": ""
    },
    "2026009": {
        "id": "2026009",
        "secretId": "2026009",
        "name": "",
        "courseName": "",
        "grantName": "",
        "graduationYear": "2026",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "2026009",
        "email": "",
        "phone": "",
        "photoUrl": "",
        "certificateImageUrl": ""
    },
    "SH-2025-010": {
        "id": "SH-2025-010",
        "secretId": "SH-2025-010",
        "name": "هناء عاطف محمود",
        "courseName": "تدريب المدربين TOT",
        "grantName": "تدريب المدربين TOT",
        "graduationYear": "2025",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "SH-2025-010",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D9%87%D9%86%D8%A7%D8%A1&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": ""
    },
    "SH-2025-011": {
        "id": "SH-2025-011",
        "secretId": "SH-2025-011",
        "name": "أحمد فتحي السيد",
        "courseName": "تأهيل اخصائي دعم نفسي",
        "grantName": "تأهيل اخصائي دعم نفسي",
        "graduationYear": "2025",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "SH-2025-011",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D8%A3%D8%AD%D9%85%D8%AF&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": ""
    },
    "SH-2025-012": {
        "id": "SH-2025-012",
        "secretId": "SH-2025-012",
        "name": "سعاد محمد رضا",
        "courseName": "تأهيل اخصائي تربية خاصة",
        "grantName": "تأهيل اخصائي تربية خاصة",
        "graduationYear": "2025",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "SH-2025-012",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D8%B3%D8%B9%D8%A7%D8%AF&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": ""
    },
    "SH-2025-013": {
        "id": "SH-2025-013",
        "secretId": "SH-2025-013",
        "name": "طارق ياسر أحمد",
        "courseName": "تأهيل اخصائي اكلينكي",
        "grantName": "تأهيل اخصائي اكلينكي",
        "graduationYear": "2025",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "SH-2025-013",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D8%B7%D8%A7%D8%B1%D9%82&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": ""
    },
    "SH-2025-014": {
        "id": "SH-2025-014",
        "secretId": "SH-2025-014",
        "name": "منى عبدالرحمن سليمان",
        "courseName": "تأهيل اخصائي صحة نفسية",
        "grantName": "تأهيل اخصائي صحة نفسية",
        "graduationYear": "2025",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "SH-2025-014",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D9%85%D9%86%D9%89&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": ""
    },
    "SH-2025-015": {
        "id": "SH-2025-015",
        "secretId": "SH-2025-015",
        "name": "سامي أحمد عبدالله",
        "courseName": "تأهيل مرشد أسري",
        "grantName": "تأهيل مرشد أسري",
        "graduationYear": "2025",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "SH-2025-015",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D8%B3%D8%A7%D9%85%D9%8A&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": ""
    },
    "SH-2025-016": {
        "id": "SH-2025-016",
        "secretId": "SH-2025-016",
        "name": "رباب خالد محمد",
        "courseName": "تدريب المدربين TOT",
        "grantName": "تدريب المدربين TOT",
        "graduationYear": "2025",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "SH-2025-016",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D8%B1%D8%A8%D8%A7%D8%A8&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": ""
    },
    "SH-2025-017": {
        "id": "SH-2025-017",
        "secretId": "SH-2025-017",
        "name": "أمير جمال حسن",
        "courseName": "تأهيل اخصائي دعم نفسي",
        "grantName": "تأهيل اخصائي دعم نفسي",
        "graduationYear": "2025",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "SH-2025-017",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D8%A3%D9%85%D9%8A%D8%B1&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": ""
    },
    "SH-2025-018": {
        "id": "SH-2025-018",
        "secretId": "SH-2025-018",
        "name": "حنان علي يوسف",
        "courseName": "تأهيل اخصائي تربية خاصة",
        "grantName": "تأهيل اخصائي تربية خاصة",
        "graduationYear": "2025",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "SH-2025-018",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D8%AD%D9%86%D8%A7%D9%86&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": ""
    },
    "SH-2025-019": {
        "id": "SH-2025-019",
        "secretId": "SH-2025-019",
        "name": "مروان ياسر إبراهيم",
        "courseName": "تأهيل اخصائي اكلينكي",
        "grantName": "تأهيل اخصائي اكلينكي",
        "graduationYear": "2025",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "SH-2025-019",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D9%85%D8%B1%D9%88%D8%A7%D9%86&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": ""
    },
    "SH-2025-020": {
        "id": "SH-2025-020",
        "secretId": "SH-2025-020",
        "name": "إيمان صلاح الدين",
        "courseName": "تأهيل اخصائي صحة نفسية",
        "grantName": "تأهيل اخصائي صحة نفسية",
        "graduationYear": "2025",
        "date": "",
        "grade": "",
        "duration": "",
        "doctorName": "د. محمد قطب",
        "certificateNumber": "SH-2025-020",
        "email": "",
        "phone": "",
        "photoUrl": "https://ui-avatars.com/api/?name=%D8%A5%D9%8A%D9%85%D8%A7%D9%86&background=1B4B8C&color=fff&size=300",
        "certificateImageUrl": ""
    }
};
